# 
name: Docker CI/CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t climateapp:latest ./docker-app

      - name: Stop old container
        run: |
          docker stop climateapp || true
          docker rm climateapp || true

      - name: Run updated container
        run: docker run -d -p 8080:80 --name climateapp climateapp:latest
